myf = open(r'C:\Users\George~\Desktop\mydemo.txt')
txt = myf.read()
print(txt)
myf.close()

print('-'*50)
myf = open(r'C:\Users\George~\Desktop\mydemo.txt','a+')
myf.write("\n这是我刚加的")
myf.seek(0)
myf = open(r'C:\Users\George~\Desktop\mydemo.txt','a+',newline='\n')
txt = myf.write("再加一行字")
myf.close()
txt = myf.read()
print(txt)